export const tokenConstants = {

    TOKEN_REQUEST: 'TOKEN_LOGIN_REQUEST',
    TOKEN_SUCCESS: 'TOKEN_LOGIN_SUCCESS',
    TOKEN_FAILURE: 'TOKEN_LOGIN_FAILURE',
    TOKEN_LOGOUT: 'TOKEN_LOGOUT'
     
};